---
version: "3.9"

volumes:
  ovos_skills:
    driver: local

services:
  ovos_messagebus:
    container_name: ovos_messagebus
    hostname: ovos_messagebus
    restart: unless-stopped
    image: smartgic/ovos-messagebus:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${CACHE_FOLDER}:/tmp/mycroft

  ovos_gui_websocket:
    container_name: ovos_gui_websocket
    hostname: ovos_gui_websocket
    restart: unless-stopped
    image: smartgic/ovos-gui-websocket:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${CACHE_FOLDER}:/tmp/mycroft
    depends_on:
      - ovos_messagebus

  ovos_phal:
    container_name: ovos_phal
    hostname: ovos_phal
    restart: unless-stopped
    image: smartgic/ovos-phal:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus

  ovos_phal_admin:
    container_name: ovos_phal_admin
    hostname: ovos_phal_admin
    restart: unless-stopped
    image: smartgic/ovos-phal-admin:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - /sys:/sys:ro
      - /dev:/dev:ro
    depends_on:
      - ovos_messagebus

  ovos_listener:
    container_name: ovos_listener
    hostname: ovos_listener
    restart: unless-stopped
    image: smartgic/ovos-listener:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${MODELS_DATA}:/home/${OVOS_USER}/.local/share/precise-lite
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${VOSK_DATA}:/home/${OVOS_USER}/.local/share/vosk
    depends_on:
      - ovos_messagebus
      - ovos_phal

  ovos_audio:
    container_name: ovos_audio
    hostname: ovos_audio
    restart: unless-stopped
    image: smartgic/ovos-audio:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus
      - ovos_phal

  ovos_skills:
    container_name: ovos_skills
    hostname: ovos_skills
    restart: unless-stopped
    image: smartgic/ovos-skills:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${CACHE_FOLDER}:/tmp/mycroft
      - ${SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
    depends_on:
      - ovos_messagebus
      - ovos_phal
